language: objective-c
osx_image: xcode8.1

before_install:
    # - brew update
    # - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
    
script:
    - pushd vendor/sqlcipher
    - git submodule init
    - git submodule update
    - ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="-lcrypto"
    - make
    - popd
    - pushd vendor/sqlcipher/sqlcipher.xcodeproj
    - cp project.pbxproj proj.tmp
    - sed 's/ CFLAGS=../ CFLAGS=\\"-miphoneos-version-min=6.0 /' proj.tmp > project.pbxproj
    - popd
    - cd exampleProjects/IncrementalStore
    # 32-bit tests
    # - xctool -sdk iphonesimulator -scheme "Incremental Store Demo" run-tests -destination "platform=iOS Simulator,name=iPhone 5"
    # 64-bit tests
    - xcodebuild -sdk iphonesimulator -scheme "Incremental Store Demo" build test -destination "platform=iOS Simulator,name=iPhone 5s"
    - sleep 20
    
    